DROP TABLE IF EXISTS TEST_CASES;
CREATE TABLE TEST_CASES (
  IRN TEXT,
  TITLE TEXT,
  DATE_UPDATED TIMESTAMP
);

INSERT INTO TEST_CASES (IRN, TITLE, DATE_UPDATED) VALUES ('P0100973', 'Software for connecting SQL database with timekeeping API', '2019-08-06');
INSERT INTO TEST_CASES (IRN, TITLE, DATE_UPDATED) VALUES ('P0436021', 'Method and apparatus for jumping through hoops', '2019-07-21');
INSERT INTO TEST_CASES (IRN, TITLE, DATE_UPDATED) VALUES ('P0070709', 'Toy building brick', '2014-11-01');

DROP TABLE IF EXISTS TEST_PROJECTS;
CREATE TABLE TEST_PROJECTS (
  PRJ_ID INTEGER PRIMARY KEY,
  IRN TEXT,
  DESCRIPTION TEXT
);

INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION) VALUES (80000, 'P0436021', 'Application - Draft 1');
INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION) VALUES (80001, 'P0436021', 'Application - Draft 2');
INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION) VALUES (80002, 'P0070709', 'Response');

DROP TABLE IF EXISTS TEST_TAG_METADATA;
CREATE TABLE TEST_TAG_METADATA (
  META_ID INTEGER PRIMARY KEY,
  IRN TEXT,
  URL TEXT,
  COUNTRY TEXT,
  LOCATION TEXT
);

INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION) VALUES (1, 'P0100973', 'Germany', 'Berlin');
INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION) VALUES (2, 'P0436021', 'Italy', 'Rome');
INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION) VALUES (3, 'P0070709', 'Australia', 'Canberra');
