DROP TABLE IF EXISTS TEST_CASES;
CREATE TABLE TEST_CASES
(
    IRN          TEXT,
    TITLE        TEXT,
    URL          TEXT,
    DATE_UPDATED TIMESTAMP
);

INSERT INTO TEST_CASES (IRN, TITLE, URL, DATE_UPDATED)
VALUES ('P0100973', 'Software for connecting SQL database with timekeeping API', 'http://www.google.com', '2019-08-06');
INSERT INTO TEST_CASES (IRN, TITLE, URL, DATE_UPDATED)
VALUES ('P0436021', 'Method and apparatus for jumping through hoops', 'http://www.google.com', '2019-07-21');
INSERT INTO TEST_CASES (IRN, TITLE, URL, DATE_UPDATED)
VALUES ('P0070709', 'Toy building brick', 'http://www.google.com', '2014-11-01');

DROP TABLE IF EXISTS TEST_PROJECTS;
CREATE TABLE TEST_PROJECTS
(
    PRJ_ID      INTEGER PRIMARY KEY,
    IRN         TEXT,
    DESCRIPTION TEXT
);

INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION)
VALUES (80000, 'P0436021', 'Application - Draft 1');
INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION)
VALUES (80001, 'P0436021', 'Application - Draft 2');
INSERT INTO TEST_PROJECTS (PRJ_ID, IRN, DESCRIPTION)
VALUES (80002, 'P0070709', 'Response');

DROP TABLE IF EXISTS TEST_TAG_METADATA;
CREATE TABLE TEST_TAG_METADATA
(
    META_ID  INTEGER PRIMARY KEY,
    IRN      TEXT,
    COUNTRY  TEXT,
    LOCATION TEXT
);

INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION)
VALUES (1, 'P0100973', 'Germany', 'Berlin');
INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION)
VALUES (2, 'P0436021', 'Italy', 'Rome');
INSERT INTO TEST_TAG_METADATA (META_ID, IRN, COUNTRY, LOCATION)
VALUES (3, 'P0070709', 'Australia', 'Canberra');

DROP TABLE IF EXISTS TEST_ACTIVITYCODES;
CREATE TABLE TEST_ACTIVITYCODES (
  ACTIVITYCODE TEXT,
  ACTIVITYNAME TEXT,
  ACTIVITYDESCRIPTION TEXT
);

INSERT INTO TEST_ACTIVITYCODES (ACTIVITYCODE, ACTIVITYNAME, ACTIVITYDESCRIPTION)
VALUES ('12345', 'Billable', 'Billable description');
INSERT INTO TEST_ACTIVITYCODES (ACTIVITYCODE, ACTIVITYNAME, ACTIVITYDESCRIPTION)
VALUES ('23456', 'Non-Billable', 'Non-Billable description');
INSERT INTO TEST_ACTIVITYCODES (ACTIVITYCODE, ACTIVITYNAME, ACTIVITYDESCRIPTION)
VALUES ('34567', 'Default', 'Default description');
