---
version: 2
plan:
  project-key: CAPI
  key: WCS
  name: wt-connector-sql artifacts
stages:
  - ARTIFACT1:
      manual: false
      final: false
      jobs:
        - create-artifact
create-artifact:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'false'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -o errexit ; set -o errtrace ; set -o pipefail

            ./gradlew -Djib.to.auth.username=wisetimedev -Djib.to.auth.password=${bamboo.DOCKER_HUB_PASSWORD} jib
            #./gradlew -Djib.to.auth.username=wisetimedev -Djib.to.auth.password=${bamboo.DOCKER_HUB_PASSWORD} jib -PtargetArch=arm64v8
            ./gradlew -q printVersionStr > image_tag.txt
        environment: JAVA_HOME="/usr/lib/jvm/zulu-11-amd64"
  artifacts:
    - name: Docker Image Tag
      pattern: image_tag.txt
      shared: true
      required: true
variables:
  DOCKER_HUB_PASSWORD: BAMSCRT@0@0@Xdz854DoboL1BX8lGHgtiQ==
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: CAPI-WCS
plan-permissions:
  - groups:
      - bamboo-build-team
    permissions:
      - view
      - edit
      - build
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - roles:
      - logged-in
    permissions:
      - view
...
---
version: 2
deployment:
  name: _Publish wisetime-sql-connector
  source-plan: CAPI-WCS
release-naming:
  next-version-name: 1.0.25
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
  - Stable - Publish image with latest tag
  - Beta - Publish image with beta tag
Stable - Publish image with latest tag:
  triggers: &id001 []
  tasks:
    - clean
    - artifact-download:
        artifacts:
          - name: Docker Image Tag
    - script:
        interpreter: SHELL
        scripts:
          - |-
            channel="latest"
            repository=wisetime/wisetime-sql-connector
            release_image="$repository:`cat image_tag.txt`"
            echo "Publishing image $release_image to $channel"
            docker pull "$release_image"
            docker tag "$release_image" "$repository:$channel"

            #repository=wisetime/wisetime-sql-connector-arm64v8
            #release_image="$repository:`cat image_tag.txt`"
            #echo "Publishing image $release_image to $channel"
            #docker pull "$release_image"
            #docker tag "$release_image" "$repository:$channel"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
        configuration:
          commandOption: push
          pushSharedCredentialsId: '233668609'
          pushRepository: wisetime/wisetime-sql-connector:latest
          registryOption: hub
  # com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli is disabled. This state is not supported at YAML
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -o errexit ; set -o errtrace ; set -o pipefail

            author="$bamboo_ManualBuildTriggerReason_userName"
            threadKey=''
            detailsUrl="$bamboo_resultsUrl"
            buildPlan="$bamboo_shortPlanName"
            message=''

            if [ "$bamboo_jobFailed" = true ] ; then
                threadKey='failed'
                message="Bamboo deployment plan *$buildPlan* started by $author *failed*. Details on <$detailsUrl|Bamboo>."
            else
                threadKey='success'
                message="Bamboo deploy plan *$buildPlan* started by *$author* finished successfully. Details on <$detailsUrl|Bamboo>."
            fi

            curl -XPOST 'https://chat.googleapis.com/v1/spaces/AAAAkPqy808/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=kjHX7ucCYG6RmKLzCBRuyRVf8V9H36joRxJaF_-2a70%3D&threadKey='$threadKey\
              -d "{\"text\":\"$message\"}"\
              -H "Content-type: application/json"
  variables: {}
  requirements: []
  notifications: []
Beta - Publish image with beta tag:
  triggers: *id001
  tasks:
    - clean
    - artifact-download:
        artifacts:
          - name: Docker Image Tag
    - script:
        interpreter: SHELL
        scripts:
          - |-
            channel="beta"
            repository=wisetime/wisetime-sql-connector
            release_image="$repository:`cat image_tag.txt`"
            echo "Publishing image $release_image to $channel"
            docker pull "$release_image"
            docker tag "$release_image" "$repository:$channel"

            #repository=wisetime/wisetime-sql-connector-arm64v8
            #release_image="$repository:`cat image_tag.txt`"
            #echo "Publishing image $release_image to $channel"
            #docker pull "$release_image"
            #docker tag "$release_image" "$repository:$channel"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
        configuration:
          commandOption: push
          pushSharedCredentialsId: '233668609'
          pushRepository: wisetime/wisetime-sql-connector:beta
          registryOption: hub
  # com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli is disabled. This state is not supported at YAML
  final-tasks: []
  variables: {}
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: _Publish wisetime-sql-connector
deployment-permissions:
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
  - roles:
      - logged-in
    permissions:
      - view

environment-permissions:
  - Beta - Publish image with beta tag:
      - groups:
          - bamboo-deploy-team-staging
        permissions:
          - view
          - deploy
      - groups:
          - bamboo-admin
        permissions:
          - view
          - edit
          - deploy
  - Stable - Publish image with latest tag:
      - groups:
          - bamboo-deploy-team-prod
        permissions:
          - view
          - deploy
      - groups:
          - bamboo-admin
        permissions:
          - view
          - edit
          - deploy
...
